### PR TITLE
Fix missing hash bug + prevent useless RegEx call

### PR DESCRIPTION
**Pull request by SlIdE42**

### CODE REVIEW

**Comment by lobre** [comment]
I am playing with this package and I saw that no assets were cached, probably because of this "missing hash bug". Or otherwise, if it is intended behavior, I just don’t understand the code :-)

Thanks for having submitted the PR @SlIdE42. Looking forward to have this fixed!

**Comment by SlIdE42** [comment]
> I am playing with this package and I saw that no assets were cached, probably because of this "missing hash bug". Or otherwise, if it is intended behavior, I just don’t understand the code :-)
> 
> Thanks for having submitted the PR @SlIdE42. Looking forward to have this fixed!

This is the offending line of code (partly my fault):
https://github.com/benbjohnson/hashfs/blob/main/hashfs.go#L51

**Comment by lobre** [comment]
> This is the offending line of code (partly my fault):

Glad that this is a bug because I scratched my head 30 minutes on that `open` function yesterday saying to myself that I missed something ^^.

**Comment by benbjohnson** [comment]
Thanks, @SlIdE42. Released as https://github.com/benbjohnson/hashfs/releases/tag/v0.2.1

**Pull request merged**
